### ISSUE TITLE
Exclude files from changlog

### ISSUE THREAD

**Issue by donavanbecker** [patrickjahns/version-drafter-action#18]
Is there a way to exclude files from being check when running this workflow?

**Comment by patrickjahns** [comment]
@donavanbecker 

The question is not quite clear to me. The `version-drafter-action` currently calculates the next semantic version based on labels on pull_request ( as describe here https://github.com/patrickjahns/version-drafter-action#configuration ).

It will not check any files

**Comment by donavanbecker** [comment]
sorry @patrickjahns this was meant for [patrickjahns/chlgr](https://github.com/patrickjahns/chlgr)
