### ISSUE TITLE
Github action using Node 12 will stop working on September 27th

### ISSUE THREAD

**Issue by w3stling** [patrickjahns/version-drafter-action#368]
GitHub Actions: All Actions will begin running on Node16 instead of Node12
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

From link above:
`For Actions maintainers: Update your actions to run on Node 16 instead of Node 12`

I created PR #367 for this.

**Comment by patrickjahns** [comment]
@w3stling - thank you for taking care.
I've just published the release https://github.com/patrickjahns/version-drafter-action/releases/tag/v1.3.0 with the updated changes
