### ISSUE TITLE
Crash with "runnerIsActions is not a function"

### ISSUE THREAD

**Issue by neubi4** [patrickjahns/version-drafter-action#370]
Hi,

at the moment, patrickjahns/version-drafter-action@v1 crashes with this error message:
```
07:06:58.762Z ERROR event: runnerIsActions is not a function (id=83de8d34-ccb8-4e5d-9e69-5e0a1c792fd3)
  TypeError: runnerIsActions is not a function
      at getConfig (/app/lib/config.js:23:9)
      at async /app/index.js:13:18
  --
  event: {
    "event": "push",
    "id": "83de8d34-ccb8-4e5d-9e69-5e0a1c792fd3",
    "repository": "telekom-mms/fortilib"
  }
```

Full ci log: https://github.com/telekom-mms/fortilib/actions/runs/10022407512/job/27733633120

Do you have a idea whats broken?

**Comment by BeArchiTek** [comment]
Hello @neubi4 

I got the same issue and solved it by creating the `version-drafter.yml` file in my .github folder.

I hope it solved your issue too.

**Comment by neubi4** [comment]
Thanks @BeArchiTek, this fixed our issue :)
